//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Infraestructure.Models.Metadata;

    [MetadataType(typeof(ActivoMetadata))]
    public partial class Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activo()
        {
            this.Depreciacion = new HashSet<Depreciacion>();
        }
    
        public string IdActivo { get; set; }
        public decimal NumSerie { get; set; }
        public int IdTipoActivo { get; set; }
        public string Modelo { get; set; }
        public System.DateTime FechCompra { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoDolares { get; set; }
        public decimal ValorActual { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechVenceGarantia { get; set; }
        public string Asegurador { get; set; }
        public System.DateTime FechVenceSeguro { get; set; }
        public string CondicionActivo { get; set; }
        public byte[] FotoFactura { get; set; }
        public byte[] FotoActivo { get; set; }
        public int IdMarca { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual TipoActivo TipoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depreciacion> Depreciacion { get; set; }
    }
}
