//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using static Infraestructure.Models.Metadata;

  
    public partial class Depreciacion
    {
        public string IdDepreciacion { get; set; }
        public string IdActivo { get; set; }
        public decimal DepreciacionMensual { get; set; }
        public decimal ValorActual { get; set; }
        public int NumeroMes { get; set; }
        public decimal ValorFinal { get; set; }
    
        public virtual Activo Activo { get; set; }
    }
}
